version: 2.1
jobs:
  test:
    docker:
      - image: golang:latest
    resource_class: small
    steps:
      - checkout
      - run:
          name: "dependencies"
          command: "go get"
      - run:
          name: "Run tests"
          command: "go test"
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    docker:
      - image: golang:latest
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "build"
          command: |
             mkdir artifacts && \
             env GOOS=darwin GOARCH=amd64 go build -o artifacts/kumquat-darwin-amd64 && \
             env GOOS=darwin GOARCH=arm64 go build -o artifacts/kumquat-darwin-arm64 && \
             env GOOS=linux GOARCH=amd64 go build -o artifacts/kumquat-linux-amd64
      - persist_to_workspace:
          root: .
          paths:
            - artifacts
  release:
    docker:
      - image: cibuilds/github:0.10
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            VERSION=${CIRCLE_TAG}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
  dockerPush:
    docker:
      - image: docker:17.05.0-ce-git
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          command: |
            tag=`echo ${CIRCLE_TAG} | cut -b 2-999`
            majmin=`echo $tag | cut -d . -f 1-2`
            maj=`echo $tag | cut -d . -f 1`
            docker build --pull -t theirish81/kumquat:${tag} .
            docker tag theirish81/kumquat:${tag} theirish81/kumquat:${majmin}
            docker tag theirish81/kumquat:${tag} theirish81/kumquat:${maj}
            docker tag theirish81/kumquat:${tag} theirish81/kumquat:latest
            docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
            docker push theirish81/kumquat:${tag}
            docker push theirish81/kumquat:${majmin}
            docker push theirish81/kumquat:${maj}
            docker push theirish81/kumquat:latest

workflows:
  build-workflow:
    jobs:
      - test:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - build:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - dockerPush:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/